/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button_stop_click(GButton source, GEvent event) { //_CODE_:button_stop:689144:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button_stop:689144:

public void button_start_click(GButton source, GEvent event) { //_CODE_:button_start:371640:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button_start:371640:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:993589:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:993589:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:714596:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:714596:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button_stop = new GButton(this, 520, 80, 110, 30);
  button_stop.setText("Stop");
  button_stop.setLocalColorScheme(GCScheme.RED_SCHEME);
  button_stop.addEventHandler(this, "button_stop_click");
  button_start = new GButton(this, 520, 40, 110, 30);
  button_start.setText("Start");
  button_start.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button_start.addEventHandler(this, "button_start_click");
  view1 = new GView(this, 10, 10, 500, 330, JAVA2D);
  dropList1 = new GDropList(this, 520, 10, 110, 80, 3, 10);
  dropList1.setItems(loadStrings("list_993589"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  textfield1 = new GTextField(this, 110, 380, 180, 20, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(this, 90, 350, 110, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Statistics");
  label1.setOpaque(false);
  label2 = new GLabel(this, 10, 380, 90, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Max Deviation");
  label2.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton button_stop; 
GButton button_start; 
GView view1; 
GDropList dropList1; 
GTextField textfield1; 
GLabel label1; 
GLabel label2; 
